In [1]:
import pandas as pd
import sqlite3
from logger_master import get_logger
import json 
import time
import random
from datetime import datetime
import requests
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import fake_useragent
from bs4 import BeautifulSoup
import os

/Users/anastasia/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
db_path = os.path.join(os.getcwd(), 'GP_DB.db')

connection = sqlite3.connect(db_path)
cursor = connection.cursor()

In [5]:
data = pd.read_sql_query("SELECT * FROM vacancies", connection)
data.head(5)

,id,hh_vac_id,hh_vac_link,title,experience,employment,schedule,salary_raw,salary_from,salary_to,currency,employer,address_raw,area,skills,published_at
0,1,131963477,https://hh.ru/vacancy/131963477,Senior AI Multiagent Systems Engineer,Опыт более 6 лет,None,None,"400 000 – 700 000₽за месяц,на руки",NaN,NaN,None,Simplenight,Москва,None,None,None
1,2,132530194,https://hh.ru/vacancy/132530194,Middle+ AI-инженер,Опыт 1-3 года,None,None,"до320 000₽за месяц,до вычета налогов",NaN,NaN,None,Точка Банк,Москва,None,[],2026-04-27T18:53:55.340855
2,3,131744414,https://hh.ru/vacancy/131744414,Prompt Engineer / AI‑редактор (нейросети и авт...,Опыт 1-3 года,полная,полный день,"80 000 – 100 000₽за месяц,на руки",80000.0,100000.0,RUR,ДЖЕЙКЕТ РАБОТА,Москва,Москва,[],2026-04-27T18:54:50.686408
3,4,131657596,https://hh.ru/vacancy/131657596,AI Engineer (International AI Brand),Опыт более 6 лет,None,None,"5 000 – 7 000$за месяц,на руки",NaN,NaN,None,MT Lab,Москва,None,None,None
4,5,131873094,https://hh.ru/vacancy/131873094,Senior MLOps & BlockchainOps Engineer (DevOps ...,Опыт более 6 лет,полная,полный день,"300 000 – 600 000₽за месяц,на руки",300000.0,600000.0,RUR,Simplenight,Москва,Москва,[],2026-04-27T18:57:51.653715

In [ ]:
data['raw_page'] = None
data

,id,hh_vac_id,hh_vac_link,title,experience,employment,schedule,salary_raw,salary_from,salary_to,currency,employer,address_raw,area,skills,published_at,raw_page
0,1,131963477,https://hh.ru/vacancy/131963477,Senior AI Multiagent Systems Engineer,Опыт более 6 лет,None,None,"400 000 – 700 000₽за месяц,на руки",NaN,NaN,None,Simplenight,Москва,None,None,None,None
1,2,132530194,https://hh.ru/vacancy/132530194,Middle+ AI-инженер,Опыт 1-3 года,None,None,"до320 000₽за месяц,до вычета налогов",NaN,NaN,None,Точка Банк,Москва,None,[],2026-04-27T18:53:55.340855,None
2,3,131744414,https://hh.ru/vacancy/131744414,Prompt Engineer / AI‑редактор (нейросети и авт...,Опыт 1-3 года,полная,полный день,"80 000 – 100 000₽за месяц,на руки",80000.0,100000.0,RUR,ДЖЕЙКЕТ РАБОТА,Москва,Москва,[],2026-04-27T18:54:50.686408,None
3,4,131657596,https://hh.ru/vacancy/131657596,AI Engineer (International AI Brand),Опыт более 6 лет,None,None,"5 000 – 7 000$за месяц,на руки",NaN,NaN,None,MT Lab,Москва,None,None,None,None
4,5,131873094,https://hh.ru/vacancy/131873094,Senior MLOps & BlockchainOps Engineer (DevOps ...,Опыт более 6 лет,полная,полный день,"300 000 – 600 000₽за месяц,на руки",300000.0,600000.0,RUR,Simplenight,Москва,Москва,[],2026-04-27T18:57:51.653715,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26806,26807,132480631,https://hh.ru/vacancy/132480631,Помощник юриста,Без опыта,None,None,"30 000 – 60 000 ₽ за месяц, на руки",NaN,NaN,None,ИП Рыжова Екатерина Вячеславовна,"Орёл, Наугорское шоссе, 5",None,None,None,None
26807,26808,131274336,https://hh.ru/vacancy/131274336,Стажер в юридический отдел/Помощник юриста,Без опыта,None,None,"от 40 000 ₽ за месяц, на руки",NaN,NaN,None,ООО Бюро арбитражных споров Феникс,Санкт-Петербург,None,None,None,None
26808,26809,132283776,https://hh.ru/vacancy/132283776,Юрист,Опыт 3-6 лет,None,None,"150 000 ₽ за месяц, до вычета налогов",NaN,NaN,None,"Персонал-Exclusive, Первое рекрутинговое агент...",Москва,None,None,None,None
26809,26810,132008277,https://hh.ru/vacancy/132008277,Помощник юриста,Без опыта,None,None,"60 000 – 75 000 ₽ за месяц, на руки",NaN,NaN,None,Юридическая компания Аргумент,Новосибирск,None,None,None,None
26810,26811,131733809,https://hh.ru/vacancy/131733809,Юрист в логистическую компанию,Опыт 3-6 лет,None,None,"от 130 000 ₽ за месяц, на руки",NaN,NaN,None,НОВЕЛКО,Москва,None,None,None,None

In [15]:
for index, row in data.iterrows():
    print(index)
    if row['raw_page']:
        pass
    else:
        try:
            headers = {
                'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36'
            }

            resp = requests.get(row['hh_vac_link'], headers=headers, timeout=5)

            if resp.status_code == 200:
                text = resp.text
                data.loc[index, 'raw_page'] = resp.text
                print(f'УСПЕХ: {text[:200]}')
            else:
                print(f'ОШИБКА --- {resp.status_code}')

        except Exception as ex:
            print(f'код упал с {ex}')
            
        time.sleep(0.05)

0
1
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132530194 (Caused by ConnectTimeoutError(<HTTPSConnection(host='hh.ru', port=443) at 0x177d83050>, 'Connection to hh.ru timed out. (connect timeout=5)'))
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132385260 (Caused by ConnectTimeoutError(<HTTPSConnection(host='hh.ru', port=443) at 0x177dbcc50>, 'Connection to hh.ru timed out. (connect timeout=5)'))
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Read timed out. (read timeout=5)
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
ОШИБКА --- 403
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 17773126184129acfe8169d929d69025--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
530
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 17773126291210448527a7972536f022--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
531
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312635838f75f5315b7ea27a1025--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
532
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312647091c35587f29a2a51dd022--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
533
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 17773126512662d1b64247d88474a027--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
534
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312653459aec9a6da0be71d41025--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
535
536
537
538
539
540
541
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312655895c1a90e0a373f37b7023--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
542
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 17773126584846e44613b80b3fff0028--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
543
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Read timed out. (read timeout=5)
544
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132325807 (Caused by ConnectTimeoutError(<HTTPSConnection(host='hh.ru', port=443) at 0x177d81690>, 'Connection to hh.ru timed out. (connect timeout=5)'))
545
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132319550 (Caused by ConnectTimeoutError(<HTTPSConnection(host='hh.ru', port=443) at 0x177dbe910>, 'Connection to hh.ru timed out. (connect timeout=5)'))
546
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132319208 (Caused by ConnectTimeoutError(<HTTPSConnection(host='hh.ru', port=443) at 0x177de2610>, 'Connection to hh.ru timed out. (connect timeout=5)'))
547
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132320180 (Caused by ConnectTimeoutError(<HTTPSConnection(host='hh.ru', port=443) at 0x16a2e6bd0>, 'Connection to hh.ru timed out. (connect timeout=5)'))
548
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132316772 (Caused by ConnectTimeoutError(<HTTPSConnection(host='hh.ru', port=443) at 0x177af0a10>, 'Connection to hh.ru timed out. (connect timeout=5)'))
549
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132316235 (Caused by ConnectTimeoutError(<HTTPSConnection(host='hh.ru', port=443) at 0x177dbe890>, 'Connection to hh.ru timed out. (connect timeout=5)'))
550
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132315734 (Caused by ConnectTimeoutError(<HTTPSConnection(host='hh.ru', port=443) at 0x177d98690>, 'Connection to hh.ru timed out. (connect timeout=5)'))
551
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/131979156 (Caused by ConnectTimeoutError(<HTTPSConnection(host='hh.ru', port=443) at 0x177d81690>, 'Connection to hh.ru timed out. (connect timeout=5)'))
552
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132311976 (Caused by ConnectTimeoutError(<HTTPSConnection(host='hh.ru', port=443) at 0x177de2a90>, 'Connection to hh.ru timed out. (connect timeout=5)'))
553
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/130946937 (Caused by ConnectTimeoutError(<HTTPSConnection(host='hh.ru', port=443) at 0x16a28d750>, 'Connection to hh.ru timed out. (connect timeout=5)'))
554
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132301038 (Caused by ConnectTimeoutError(<HTTPSConnection(host='hh.ru', port=443) at 0x177d9a350>, 'Connection to hh.ru timed out. (connect timeout=5)'))
555
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132298639 (Caused by ConnectTimeoutError(<HTTPSConnection(host='hh.ru', port=443) at 0x16a254390>, 'Connection to hh.ru timed out. (connect timeout=5)'))
556
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132296105 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
557
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132305661 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
558
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132305205 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
559
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132299887 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
560
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/131494234 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
561
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132301565 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
562
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132303839 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
563
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/131805009 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
564
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 177731280688071effcbedeb00126025--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
565
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312807826aac674ece7f97066025--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
566
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312808273671c52e12b04e8bd023--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
567
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312808854082e662288b06515026--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
568
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 17773128094679cd84781535323eb023--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
569
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312811378b8a85329c76120eb027--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
570
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/131794617 (Caused by ConnectTimeoutError(<HTTPSConnection(host='hh.ru', port=443) at 0x177d98290>, 'Connection to hh.ru timed out. (connect timeout=5)'))
571
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132283523 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
572
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132290164 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
573
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132282917 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
574
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132190081 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
575
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132294694 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
576
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132291294 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
577
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132291687 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
578
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132292082 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
579
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132291066 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
580
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132279625 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
581
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132280241 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
582
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/126507919 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
583
код упал с HTTPSConnectionPool(host='hh.ru', port=443): Max retries exceeded with url: /vacancy/132285610 (Caused by NameResolutionError("HTTPSConnection(host='hh.ru', port=443): Failed to resolve 'hh.ru' ([Errno 8] nodename nor servname provided, or not known)"))
584
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 17773128681618445e3b999f05f41022--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
585
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312870831f6220ea61866e041027--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
586
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312873756f2e1a082fb7f0996023--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
587
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312877049126898e4abec5c68027--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
588
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312880863989dfb9203acf0f2028--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
589
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312886480018d653f466bf22d026--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
590
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 177731289087773d98aa40a00af7b021--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
591
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312899700becaef231ac57ddc028--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
592
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312903301c631f7e3eba35d0d026--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
593
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312906075ac86928f69a2395e026--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
594
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312910918e327dad1c582aa88026--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
595
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 17773129175892f87f298a9cff9f6028--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
596
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312922794abaebc73da67b288024--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
597
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312926555f29cac0ca9cd55d9022--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
598
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312929736fe6435db8236698d025--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
599
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312933943c5f4779cfe7827bb026--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
600
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 177731293726678163b9b7b00c411024--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
601
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 17773129418546a77f33d7a11888f021--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
602
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 177731294416172567d7a0e87779a025--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
603
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 17773129456286ecc16b25ccd6685023--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
604
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312948099e1063868a8b6ff94021--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
605
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 17773129519088b971a148dbf9eaa026--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
606
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312954518318464762a9dec95025--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
607
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 1777312956759fe04ed61c8594a4b028--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
608
УСПЕХ: <!DOCTYPE html>
<html class="desktop" lang="ru"><!--request: 17773129589490ee27c6db421db18023--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatib
609
УСПЕХ: <!DOCTYPE html>

KeyboardInterrupt:

In [16]:
data['raw_page']

0        <!DOCTYPE html>\n<html class="desktop" lang="r...
1                                                     None
2        <!DOCTYPE html>\n<html class="desktop" lang="r...
3        <!DOCTYPE html>\n<html class="desktop" lang="r...
4        <!DOCTYPE html>\n<html class="desktop" lang="r...
                               ...
26806                                                 None
26807                                                 None
26808                                                 None
26809                                                 None
26810                                                 None
Name: raw_page, Length: 26811, dtype: object

In [17]:
data.to_excel('batch_v1_size_1000.xlsx')